const year = document.getElementById('year');
if (year) year.textContent = new Date().getFullYear();
const menuToggle = document.querySelector('[data-menu-toggle]'); const menu = document.querySelector('[data-menu]');
menuToggle?.addEventListener('click', () => { const open = menu.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', String(open)); });
menu?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { menu.classList.remove('is-open'); menuToggle.setAttribute('aria-expanded', 'false'); }));
document.addEventListener('click', (event) => { if (!event.target.closest('[data-header]')) { menu?.classList.remove('is-open'); menuToggle?.setAttribute('aria-expanded', 'false'); } });
const endpoint = 'https://kobes-betting-hub-checkout.kobedirwin.workers.dev'; const sessionId = new URLSearchParams(window.location.search).get('session_id') || ''; const status = document.querySelector('[data-status]'); const panel = document.querySelector('[data-panel]'); const message = document.querySelector('[data-message]');
const showStep = (step) => document.querySelectorAll('[data-step]').forEach((item) => { item.hidden = item.dataset.step !== step; }); const showMessage = (value) => { if (message) message.textContent = value; };
async function loadMembership() { if (!sessionId) { status.textContent = 'Open this page from your checkout confirmation link so we can securely identify your membership.'; return; } try { const response = await fetch(`${endpoint}/cancel/offer?session_id=${encodeURIComponent(sessionId)}`); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'We could not verify this membership session.'); panel.hidden = false; status.textContent = result.retentionAvailable ? 'Choose an option below. You can cancel at any time.' : 'Your one-time retention offer has already been used. You can still cancel below.'; showStep(result.retentionAvailable ? 'offer20' : 'cancel'); } catch (error) { status.textContent = error.message || 'We could not verify this membership session.'; } }
document.querySelectorAll('[data-next]').forEach((button) => button.addEventListener('click', () => showStep(button.dataset.next)));
document.querySelectorAll('[data-retain]').forEach((button) => button.addEventListener('click', async () => { document.querySelectorAll('button').forEach((item) => { item.disabled = true; }); showMessage('Applying your one-time offer securely…'); try { const response = await fetch(`${endpoint}/cancel/retain`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session_id: sessionId, percent: Number(button.dataset.retain) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'This offer could not be applied.'); status.textContent = `Your ${button.dataset.retain}% one-time offer is active for the next month.`; showMessage('You’re all set. Your membership remains active.'); panel.querySelectorAll('[data-step]').forEach((item) => { item.hidden = true; }); } catch (error) { showMessage(error.message || 'This offer could not be applied.'); document.querySelectorAll('button').forEach((item) => { item.disabled = false; }); } }));
document.querySelector('[data-cancel]')?.addEventListener('click', async () => { document.querySelectorAll('button').forEach((item) => { item.disabled = true; }); showMessage('Processing cancellation…'); try { const response = await fetch(`${endpoint}/cancel/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session_id: sessionId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Cancellation could not be completed.'); status.textContent = 'Your membership is canceled at the end of the current billing period.'; showMessage(result.ends_at ? `Paid Discord access remains available through ${new Date(result.ends_at * 1000).toLocaleDateString()}. No further renewal will be taken; free picks remain available.` : 'Paid Discord access remains available through the current billing period. No further renewal will be taken; free picks remain available.'); panel.querySelectorAll('[data-step]').forEach((item) => { item.hidden = true; }); } catch (error) { showMessage(error.message || 'Cancellation could not be completed.'); document.querySelectorAll('button').forEach((item) => { item.disabled = false; }); } });
loadMembership();
