/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.instagram.jsonc --include-runtime=false --strict-vars=false cloudflare/instagram-configuration.d.ts` (hash: 56e80f1c9803a49fd92ce2cbad5e20e5)
interface __BaseEnv_Env {
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	INSTAGRAM_PUBLIC_ORIGIN: string;
	INSTAGRAM_API_VERSION: string;
	INSTAGRAM_APP_ID: string;
	INSTAGRAM_APP_SECRET: string;
	INSTAGRAM_OPERATOR_SECRET: string;
	INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./bettinghub-instagram");
	}
	interface StagingEnv {
		DB: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		INSTAGRAM_PUBLIC_ORIGIN: string;
		INSTAGRAM_API_VERSION: string;
		INSTAGRAM_APP_ID: string;
		INSTAGRAM_APP_SECRET: string;
		INSTAGRAM_OPERATOR_SECRET: string;
		INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INSTAGRAM_PUBLIC_ORIGIN" | "INSTAGRAM_API_VERSION" | "INSTAGRAM_APP_ID" | "INSTAGRAM_APP_SECRET" | "INSTAGRAM_OPERATOR_SECRET" | "INSTAGRAM_TOKEN_ENCRYPTION_KEY">> {}
}
